### ISSUE TITLE
Test cases for Android application components

### ISSUE THREAD

**Issue by PatilShreyas** [PatilShreyas/NotyKT#12]
- Add Unit tests for modules `data`, `repository`, `app` etc.
- Add some integrations tests for Android.
- We can use libraries like Kotest, Mockk, etc for testing which are completely Kotlin libraries.

**Comment by PatilShreyas** [comment]
@ch8n once I'm done with initial setup. Can contribute to it

**Comment by PatilShreyas** [comment]
@ch8n @Varsha-Kulkarni If you are interested can now contribute to tests of NotyKT. I've set up a new branch [`tests`](https://github.com/PatilShreyas/NotyKT/tree/tests) for unit tests.

See some tests I added for your reference:
- [AuthInterceptorTest.kt](https://github.com/PatilShreyas/NotyKT/blob/tests/noty-android/data/remote/src/test/java/dev/shreyaspatil/noty/data/remote/interceptor/AuthInterceptorTest.kt)
- [NotyLocalNoteRepositoryTest.kt](https://github.com/PatilShreyas/NotyKT/blob/tests/noty-android/repository/src/test/java/dev/shreyaspatil/noty/repository/local/NotyLocalNoteRepositoryTest.kt)

**Comment by ch8n** [comment]
Cool I will be looking into em soon.

It would be great if we can plan how write code covering various features of the app. 

UT till repository layer would be generic but ui one could be better to write it per flow.  What's your opinion @PatilShreyas ?

**Comment by PatilShreyas** [comment]
Yeah, that would be great to have UI tests as well. Also, I'm planning ViewModel Unit tests as well.

**Comment by PatilShreyas** [comment]
Also, added sample for VM tests https://github.com/PatilShreyas/NotyKT/blob/tests/noty-android/app/src/test/java/dev/shreyaspatil/noty/view/viewmodel/NotesViewModelTest.kt

**Comment by Varsha-Kulkarni** [comment]
> Also, added a sample for VM tests: https://github.com/PatilShreyas/NotyKT/blob/tests/noty-android/app/src/test/java/dev/shreyaspatil/noty/view/viewmodel/NotesViewModelTest.kt

This is great. I will definitely start on this soon.

**Comment by PatilShreyas** [comment]
Added unit test cases in the PR #392
