### ISSUE TITLE
Background of welcome back screen is white in dark mode.

### ISSUE THREAD

**Issue by pradyum619** [PatilShreyas/NotyKT#120]
When user logs out (being in dark mode), the welcome back login prompt page has half white and half black background.
Also on back pressed, app didn't shutdown, instead same activity is recreated.

**Comment by PatilShreyas** [comment]
Thanks for reporting this issue @pradyum619. Would you like to raise PR for it?

**Comment by PatilShreyas** [comment]
Got the solution. Just removing this property would solve the issue.

https://github.com/PatilShreyas/NotyKT/blob/469ba9cef4a079b8d12a6703328d6a303c4f7137/noty-android/app/composeapp/src/main/java/dev/shreyaspatil/noty/composeapp/view/screen/LoginScreen.kt#L77

**Comment by PatilShreyas** [comment]
Fixed by #135
