### ISSUE TITLE
Note delete confirmation

### ISSUE THREAD

**Issue by yogeshpaliyal** [PatilShreyas/NotyKT#287]
It will be great to having an confirmation before deleting the note.

**Comment by kasem-sm** [comment]
Can I create a PR for this?

**Comment by kasem-sm** [comment]
There are three possible ways:
1. Show a confirmation Dialog with Yes and No and then dele.
2. Show a snack bar (for a short duration) that the note is deleted and Undo it.
3. After showing confirmation dialog and if the user clicks yes, then show a snack bar to undo the deletion (again for a short duration) and after that delete permanently.

Which one would be preferred?

**Comment by PatilShreyas** [comment]
Sure @kasem-sm. First one sounds good - simple to use.

**Comment by PatilShreyas** [comment]
@kasem-sm I've already raised PR for this. You can review it and add your suggestions if you have any: https://github.com/PatilShreyas/NotyKT/pull/298

**Comment by kasem-sm** [comment]
Looks great! Nice.
