### ISSUE TITLE
removing jcenter

### ISSUE THREAD

**Issue by sairajsawant** [PatilShreyas/NotyKT#308]
### Discussed in https://github.com/PatilShreyas/NotyKT/discussions/307

<div type='discussions-op-text'>

<sup>Originally posted by **sairajsawant** November  7, 2021</sup>
with the [sunset of jcenter](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/), current/future public dependencies won't be available - would be good to remove it to avoid gradle searching. </div>

**Comment by PatilShreyas** [comment]
Yeah @sairajsawant 💯. After seeing dependencies, I guess we can easily remove jcenter().

**Comment by PatilShreyas** [comment]
Would you like to contribute to this?

**Comment by sairajsawant** [comment]
sure!
