### ISSUE TITLE
(simpleapp) App Crashes when user click's Log Out.

### ISSUE THREAD

**Issue by kasem-sm** [PatilShreyas/NotyKT#329]
Logcat and fix for this issue attached:

Logcat: `Process: dev.shreyaspatil.noty.simpleapp, PID: 14678
    java.lang.IllegalArgumentException: Navigation action/destination dev.shreyaspatil.noty.simpleapp:id/action_notesFragment_to_loginFragment cannot be found from the current destination Destination(dev.shreyaspatil.noty.simpleapp:id/loginFragment) label=fragment_login class=dev.shreyaspatil.noty.simpleapp.view.login.LoginFragment
        at androidx.navigation.NavController.navigate(NavController.java:940)`

Fix: To check current destination before navigating.

I can contribute to this issue as well if @PatilShreyas assigns me 😅.

**Comment by PatilShreyas** [comment]
Sure @kasem-sm you can take this up

**Comment by PatilShreyas** [comment]
Assigning this to you
