### ISSUE TITLE
[Android] Feature Request: Pin notes

### ISSUE THREAD

**Issue by Varsha-Kulkarni** [PatilShreyas/NotyKT#534]
Pin notes so that they will be added to priority spot, at the top for easy access, similar to Google Keep.

We can further discuss about UI changes and state handling required to show these pinned notes.

**Comment by Varsha-Kulkarni** [comment]
Please assign this to me, Thanks.

**Comment by PatilShreyas** [comment]
This feature sounds cool to me, assigning it to you

**Comment by Varsha-Kulkarni** [comment]
Found another issue while navigating to Note Detail screen, progressDialog shows up when state is Loading. That shows up as kind of jerk (white square) while navigating. I have added pin icon for detail screen as part of options menu (screenshots attached).
OnCreateOptionsMenu gets called once before and after note state updates. The icon which is updated based on isPinned state is rerendered because of the second call and goes to default icon. When I removed the showProgressDialog while Loading, it all updates and works fine. Please let me know whether I should create another issue for this or fix it as part of this feature. 
![Screenshot_20221002-225849_Noty](https://user-images.githubusercontent.com/12287761/193469145-e2594445-ddbd-4ad1-8c48-d26c0a80a57d.jpg)
![Screenshot_20221002-225855_Noty](https://user-images.githubusercontent.com/12287761/193469146-9d60d3b5-f314-4e86-a6aa-99af8cd300f6.jpg)
![Screenshot_20221002-225900_Noty](https://user-images.githubusercontent.com/12287761/193469147-07f045be-6f38-4b04-ad62-23f6109bfd3e.jpg)

**Comment by PatilShreyas** [comment]
Good finding 👍. This can be part of this issue itself.
