### ISSUE TITLE
Keyboard retains after navigating back from Add Note or Note detail screen

### ISSUE THREAD

**Issue by Varsha-Kulkarni** [PatilShreyas/NotyKT#535]
1. Login to the app
2. Click on Add new note or click on existing note to navigate to Note Detail screen
3. add title and note, save

Actual:
 when it navigates back to notes list screen, keyboard is retained.

Expected:
Dismiss the soft keyboard

**Comment by Varsha-Kulkarni** [comment]
Please assign this to me, thanks

**Comment by PatilShreyas** [comment]
Thanks @Varsha-Kulkarni for raising this issue.

**Comment by PatilShreyas** [comment]
This is happening in simpleapp or composeapp?
