### ISSUE TITLE
Defect: Progress dialog keeps running in infinite loop

### ISSUE THREAD

**Issue by Varsha-Kulkarni** [PatilShreyas/NotyKT#536]
Steps to reproduce:

1. Login to the app.
2. Click on add note, navigate to add note detail screen
3. add title, add notes, click on save
4. navigate back to list of notes
5. click on newly added note, navigate to note detail screen
6. click on delete note button
7. once note deleted, it navigates back to list of notes screen where progress dialog keeps loading indefinitely

**Comment by Varsha-Kulkarni** [comment]
I would like to work on fixing this one, please assign this to me, Thanks

**Comment by PatilShreyas** [comment]
Thanks, @Varsha-Kulkarni for raising this issue.

**Comment by PatilShreyas** [comment]
This is happening in simpleapp or composeapp?

**Comment by Varsha-Kulkarni** [comment]
This is in simpleapp. Attaching a screen recording
[progress_dialog_loading_infinitely.webm](https://user-images.githubusercontent.com/12287761/193444691-2c6fc65d-e0ef-4db5-9ad5-d87193215384.webm)

**Comment by PatilShreyas** [comment]
Thanks for sharing the recording. What's the cause of this dialog's behaviour?

**Comment by Varsha-Kulkarni** [comment]
I think it is the same even when app loads the first time after logging in. It is because shouldSyncNotes always returns true because notes is empty in NotesFragment.
It tries to keep syncing indefinitely until there's data.

**Comment by PatilShreyas** [comment]
Oh yes, we need to fix it then
