### ISSUE TITLE
[Backend] Feature Request: Pin Notes

### ISSUE THREAD

**Issue by PatilShreyas** [PatilShreyas/NotyKT#541]
This is regarding feature "pinning notes" as discussed here: #534

This also needs to be implemented on the backend side so that the state of the ***pinning*** of notes will be persisted.

## Task

Create an API for updating the note's pin.

#### Request 

```http
PUT /note/<NOTE_ID>/pin
Content-Type: application/json
Authorization: Bearer <TOKEN>

{
  "isPinned": true
}
```

##### 1. When note gets pinned/unpinned successfully

Response Code: 200

```json
{
  "status": "SUCCESS",
  "message": "Note is pinned/unpinned successfully",
  "noteId": <NOTE ID>
}
```

##### 2. When note note exist in system

Response Code: 404

```json
{
  "status": "NOT_FOUND",
  "message": "Note not exist with ID '$noteId'"
}
```

##### 3. When unauthorized user tries to update note pin

Response Code: 401

```json
{
  "status": "UNAUTHORIZED",
  "message": "Access denied"
}
```

**Comment by mrfamouskk7** [comment]
Heyy @PatilShreyas I can take this up... should I start working on this feature??

**Comment by PatilShreyas** [comment]
Sure @mrfamouskk7. Assigning this to you.

**Comment by mrfamouskk7** [comment]
> Thanks for showing interest in contributing this @mrfamouskk7. Sure, Assigning this to you.

Thanks @PatilShreyas

**Comment by PatilShreyas** [comment]
Let me know if you need any help in setting up this project locally.

**Comment by mrfamouskk7** [comment]
Actually, I am done with local setup.
I just had a question, so `isPinned` flag will be required while fetching notes as well right? So should I include that in same PR??

**Comment by PatilShreyas** [comment]
@mrfamouskk7 Current API looks good to you?

Otherwise, we can also have two API endpoints for **pin** and **unpin** operations.

Like,

- PUT `/note/{noteId}/pin`
- PUT `/note/{noteId}/unpin`

This will not require a request body. 

WDYT?

**Comment by mrfamouskk7** [comment]
I think both the ways should okay:

- Single API with body
- Separate APIs without body

But it seems unusual/unconventional to have `PUT`/`POST` request without body.
Single API with body should be the ideal way to implement.

**Comment by mrfamouskk7** [comment]
> Yes, it'll be required to have isPinned flag in all notes response. If you're fine with doing it in the same PR, then okay. Otherwise we can also have a dedicated PR for that.

I will include in the same PR

**Comment by PatilShreyas** [comment]
> I think both the ways should okay:
> 
> - Single API with body
> - Separate APIs without body
> 
> But it seems unusual/unconventional to have `PUT`/`POST` request without body.
> Single API with body should be the ideal way to implement.

Makes sense!

**Comment by mrfamouskk7** [comment]
Heyy Shreyash, so I have a couple of suggestions:

- Pinning API can be changed from `PUT` request to a `PATCH` request. `PATCH` is more suitable because we are not updating the complete resource here.
- A new field `updated` can be added so that the most recent pinned note will be at the top

**Comment by PatilShreyas** [comment]
@mrfamouskk7 this sounds good to me. Definitely we can have `updated` field

**Comment by mrfamouskk7** [comment]
Sure... I will add those changes in the same PR :+1:
