### ISSUE TITLE
[Android] Implement API for updating Pin/Unpin state in Android app

### ISSUE THREAD

**Issue by PatilShreyas** [PatilShreyas/NotyKT#543]
Currently, all work regarding the pin/unpin feature is completed. Just API call invocation implementation is pending from the android app side. 

Once #541 is merged, the work on this issue can be started.

**Comment by Varsha-Kulkarni** [comment]
Please assign this to me, once backend issue is merged, I would love to complete this. Thanks.

**Comment by PatilShreyas** [comment]
I guess I replied on the wrong thread. NVM

Ref:
https://github.com/PatilShreyas/NotyKT/issues/547#issuecomment-1271443412
https://github.com/PatilShreyas/NotyKT/issues/547#issuecomment-1271499619

**Comment by tyaporush** [comment]
Hi @PatilShreyas Assign this to me

**Comment by PatilShreyas** [comment]
Thanks, @tyaporush for showing interest in contributing to this. Assigning this to you 😄.

**Comment by PatilShreyas** [comment]
@tyaporush Here's the REST API spec for you.

---

# REST API Specification

## Request

- Method: `PATCH`
- URL: `BASE_URL/{note-id}/pin`
- Header: `Authorization <TOKEN>`
- Body:

```json
{
  "isPinned": true/false
}
```

#### Example:

```http
PATCH https://API_BASE_URL/noteId1234/pin
Content-Type: application/json
Authorization: Bearer YOUR_AUTH_TOKEN

{
  "isPinned": true
}
```

## Response

##### 1. When note gets pinned/unpinned successfully

Response Code: 200

```json
{
  "status": "SUCCESS",
  "message": "Note is pinned/unpinned successfully",
  "noteId": <NOTE ID>
}
```

##### 2. When note note exist in system

Response Code: 404

```json
{
  "status": "NOT_FOUND",
  "message": "Note not exist with ID '$noteId'"
}
```

##### 3. When unauthorized user tries to update note pin

Response Code: 401

```json
{
  "status": "UNAUTHORIZED",
  "message": "Access denied"
}
```
