### ISSUE TITLE
Replace deprecated OptionsMenu with MenuProvider

### ISSUE THREAD

**Issue by Varsha-Kulkarni** [PatilShreyas/NotyKT#547]
Replace the usages of 
```
setHasOptionsMenu(Boolean): Unit
onCreateOptionsMenu(Menu, MenuInflater): Unit
onOptionsItemSelected(MenuItem): Boolean
onPrepareOptionsMenu(Menu): Unit
```
with [```MenuProvider```](https://developer.android.com/reference/kotlin/androidx/core/view/MenuProvider)

**Comment by PatilShreyas** [comment]
Assigning it to you

**Comment by PatilShreyas** [comment]
Hi Varsha,

Lot of folks approaching me for working on NotyKT. Since you already worked
on couple of issues and feature, If it's okay for you, can I let someone
else to work on pin backend API integration in noty android app?

**Comment by Varsha-Kulkarni** [comment]
Hi Shreyas, 

I have worked on the same pin_notes branch so that all Options Menu related code gets modified. Is that okay?

**Comment by PatilShreyas** [comment]
Yeah, works 👍
