### ISSUE TITLE
Noty Android App V2.2.1 can not signup

### ISSUE THREAD

**Issue by goredhawk** [PatilShreyas/NotyKT#617]
### Description
I download the apk from link [(https://patilshreyas.github.io/NotyKT/#/pages/noty-android/getting-started)], just below picture.
![image](https://user-images.githubusercontent.com/11162018/222599269-cd227253-6903-4250-90b0-43c5c57ad0ed.png)

and i can not signup, whenever i push the button "Create account",  the app always throw tips "Something went wrong!"

**Comment by PatilShreyas** [comment]
Thanks for raising this @goredhawk. This has been fixed in the latest release, please try again.

**Comment by xidsyed** [comment]
Problem still persists in 2.2.0

**Comment by PatilShreyas** [comment]
Actually the problem is the backend server is not up because we have run out of free quota.

**Comment by PatilShreyas** [comment]
You can run it locally. Read this doc: https://patilshreyas.github.io/NotyKT/#/pages/noty-api/setting-up-locally
