### ISSUE TITLE
Replace collectAsState with collectAsStateWithLifecycle()

### ISSUE THREAD

**Issue by iamanbansal** [PatilShreyas/NotyKT#626]
collectAsStateWithLifecycle is a composable function that collects values from a flow and represents the latest value as Compose [State](https://developer.android.com/reference/kotlin/androidx/compose/runtime/State) in a lifecycle-aware manner.

Available in `androidx.lifecycle:lifecycle-runtime-compose` from `2.6.0`

More on this [here](https://medium.com/androiddevelopers/consuming-flows-safely-in-jetpack-compose-cde014d0d5a3)

**Comment by PatilShreyas** [comment]
Thanks @iamanbansal for raising this.

**Comment by PatilShreyas** [comment]
@iamanbansal would you like to contribute on this?
