### ISSUE TITLE
Misbehaviour of Fragments

### ISSUE THREAD

**Issue by deepak-prajapatii** [PatilShreyas/NotyKT#683]
When user enter the details for login and navigate to another fragment instead of login. Now the user back press button and navigates back to the login. He is able to click on login and login successfully without entering the login details. 

Solution: pass the parameter only from fragments to the viewmodel function call instead of getting user details from UIState in viewmodel.

**Open for another solution with best approach.**

**Comment by PatilShreyas** [comment]
Thanks @deepak-prajapatii for raising this. Can you share how exactly it behaves?

**Comment by PatilShreyas** [comment]
@iam-subho still open

**Comment by mokhtarmoustafa** [comment]
I'm on It

**Comment by Vishwajith-Shettigar** [comment]
Hi @PatilShreyas , can i work on this ?

**Comment by PatilShreyas** [comment]
Due to lack of detail on the issue, I'm closing this. Feel free to reopen this if this still needs to be solved. And feel free to raise a PR for a fix!
