### ISSUE TITLE
Room database injection - Dagger hilt

### ISSUE THREAD

**Issue by sidhu18** [PatilShreyas/NotyKT#87]
Here, room database is provided through dagger hilt as a singleton in the Application component, so I think it is not required to have the singleton pattern as hilt would ensure that room database instance is a singleton.

So it would be better to build the database in DatabaseModule itself.

```kt
    @Singleton
    @Provides
    fun provideDatabase(
        @ApplicationContext context: Context
    ) = Room.databaseBuilder(
        context.applicationContext,
        NotyDatabase::class.java,
        DB_NAME
    ).addMigrations(*DatabaseMigrations.MIGRATIONS).build()

```

**Comment by PatilShreyas** [comment]
Indirectly it'll do the same task as we doing currently so I don't think we need to do this change

**Comment by sidhu18** [comment]
I mean there is no need of the getInstance method with synchronization as it is already ensured by hilt. 

```diff
- companion object {
-        private const val DB_NAME = "noty_database"
-
-        @Volatile
-       private var INSTANCE: NotyDatabase? = null
-
-        fun getInstance(context: Context): NotyDatabase {
-            val tempInstance = INSTANCE
-            if (tempInstance != null) {
-                return tempInstance
-           }
-
-            synchronized(this) {
-               val instance = Room.databaseBuilder(
-                    context.applicationContext,
-                    NotyDatabase::class.java,
-                    DB_NAME
-                ).addMigrations(*DatabaseMigrations.MIGRATIONS).build()
-
-                INSTANCE = instance
-                return instance
-            }
-        }
-    }
```

**Comment by PatilShreyas** [comment]
Still, I think this is a better approach! Because if by mistake (it won't happen) if tried to create a database manually then it would lead to trouble. Let's not make Hilt module as a GOD class

**Comment by sidhu18** [comment]
Cool, seems fair. Personally, I wouldn't choose this approach as I think there is a repetition of functionally. But still, I get the point you are making so, let's close the issue. 👍

**Comment by PatilShreyas** [comment]
Thanks, @sidhu18. Actually, I agreed with your point. Still, I thought it's better we handle that.
